# Generated by Django 6.0 on 2025-12-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='end_date',
            field=models.DateField(blank=True, help_text='Ngày kết thúc thuê xe', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_location',
            field=models.CharField(blank=True, help_text='Địa điểm nhận xe', max_length=500),
        ),
        migrations.AddField(
            model_name='order',
            name='rental_days',
            field=models.IntegerField(default=1, help_text='Số ngày thuê'),
        ),
        migrations.AddField(
            model_name='order',
            name='return_location',
            field=models.CharField(blank=True, help_text='Địa điểm trả xe', max_length=500),
        ),
        migrations.AddField(
            model_name='order',
            name='start_date',
            field=models.DateField(blank=True, help_text='Ngày bắt đầu thuê xe', null=True),
        ),
    ]
