# Generated by Django 6.0 on 2025-12-06 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('ma_kh', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ten', models.CharField(max_length=255)),
                ('sdt', models.CharField(max_length=20)),
                ('dia_chi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LoaiXe',
            fields=[
                ('ma_loai', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ten_loai', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NCC',
            fields=[
                ('ma_ncc', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ten', models.CharField(max_length=255)),
                ('dia_chi', models.CharField(max_length=255)),
                ('sdt', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('ma_nv', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ten', models.CharField(max_length=255)),
                ('sdt', models.CharField(max_length=20)),
                ('dia_chi', models.CharField(max_length=255)),
                ('gioi_tinh', models.CharField(max_length=10)),
                ('ngay_sinh', models.DateField()),
                ('chuc_vu', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HoaDonXuat',
            fields=[
                ('ma_hdx', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ngay', models.DateField()),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.khachhang')),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.nhanvien')),
            ],
        ),
        migrations.CreateModel(
            name='HoaDonNhap',
            fields=[
                ('ma_hdn', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ngay_nhap', models.DateField()),
                ('ncc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ncc')),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.nhanvien')),
            ],
        ),
        migrations.CreateModel(
            name='Xe',
            fields=[
                ('ma_xe', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ten_xe', models.CharField(max_length=255)),
                ('gia', models.IntegerField()),
                ('so_luong', models.IntegerField()),
                ('mau_sac', models.CharField(max_length=50)),
                ('loai_xe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.loaixe')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietHDX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField()),
                ('hoa_don', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hoadonxuat')),
                ('xe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.xe')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietHDN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField()),
                ('don_gia', models.IntegerField()),
                ('hoa_don', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hoadonnhap')),
                ('xe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.xe')),
            ],
        ),
        migrations.CreateModel(
            name='BaoHanh',
            fields=[
                ('ma_bh', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ngay_bh', models.DateField()),
                ('noi_dung', models.TextField()),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.khachhang')),
                ('xe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.xe')),
            ],
        ),
    ]
