# Generated by Django 5.2.9 on 2026-03-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_tenant_init'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='address',
            field=models.CharField(blank=True, help_text='Địa chỉ công ty', max_length=500),
        ),
        migrations.AddField(
            model_name='tenant',
            name='email',
            field=models.EmailField(blank=True, help_text='Email liên hệ', max_length=254),
        ),
        migrations.AddField(
            model_name='tenant',
            name='phone',
            field=models.CharField(blank=True, help_text='Số điện thoại', max_length=20),
        ),
    ]
