# Generated by Django 5.2.9 on 2026-03-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_address_tenant_email_tenant_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Mã tenant duy nhất', max_length=50),
        ),
        migrations.AddField(
            model_name='tenant',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Hoạt động'), ('INACTIVE', 'Không hoạt động')], default='ACTIVE', max_length=20),
        ),
    ]
