# Generated by Django 5.2.9 on 2026-03-04 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_code_tenant_deleted_at_tenant_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Mã tenant duy nhất', max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['code'], name='tenants_ten_code_64b1a2_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['status', 'deleted_at'], name='tenants_ten_status_6777a1_idx'),
        ),
    ]
