# Generated by GPT-5.2 on 2026-03-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0004_update_tenant_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Hoạt động"),
                    ("INACTIVE", "Không hoạt động"),
                    ("LOCKED", "Bị khóa"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="theme",
            field=models.CharField(
                choices=[
                    ("default", "Mặc định"),
                    ("car-rental", "Thuê xe"),
                    ("hotel", "Khách sạn"),
                    ("ecommerce", "Thương mại điện tử"),
                ],
                default="default",
                help_text="Giao diện website",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="logo",
            field=models.URLField(blank=True, default="", help_text="Logo công ty"),
        ),
        migrations.AddField(
            model_name="tenant",
            name="primary_color",
            field=models.CharField(
                default="#3B82F6", help_text="Màu chủ đạo (hex)", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="banner_image",
            field=models.URLField(blank=True, default="", help_text="Ảnh banner"),
        ),
        migrations.AddField(
            model_name="tenant",
            name="description",
            field=models.TextField(blank=True, default="", help_text="Mô tả công ty"),
        ),
    ]

