# Generated by Django 5.2.9 on 2026-03-03 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('tenants', '0001_tenant_init'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='tenants.tenant'),
        ),
    ]
