# Generated by Django 5.2.9 on 2026-03-03 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_tenant_init'),
        ('translation', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='translationcache',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='translationcache',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='translation_caches', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='translationkey',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='translation_keys', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='translationrequest',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='translation_requests', to='tenants.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='translationcache',
            unique_together={('tenant', 'source_text', 'source_lang', 'target_lang')},
        ),
    ]
