# Generated by Django 6.0 on 2025-12-10 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0002_order_end_date_order_pickup_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('momo', 'MoMo'), ('zalopay', 'ZaloPay'), ('vnpay', 'VNPay'), ('credit_card', 'Thẻ tín dụng'), ('paypal', 'PayPal'), ('bitcoin', 'Bitcoin')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Số tiền thanh toán (VNĐ)', max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Chờ thanh toán'), ('processing', 'Đang xử lý'), ('completed', 'Thành công'), ('failed', 'Thất bại'), ('cancelled', 'Đã hủy')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='Mã giao dịch từ gateway', max_length=255)),
                ('payment_url', models.URLField(blank=True, help_text='URL thanh toán (QR code)', max_length=500)),
                ('qr_code', models.TextField(blank=True, help_text='QR code data (base64 hoặc URL)')),
                ('callback_data', models.JSONField(blank=True, default=dict, help_text='Dữ liệu callback từ gateway')),
                ('ipn_url', models.URLField(blank=True, help_text='IPN URL để nhận callback', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='cart.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thanh toán',
                'verbose_name_plural': 'Thanh toán',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', 'status'], name='payments_pa_order_i_a76289_idx'), models.Index(fields=['transaction_id'], name='payments_pa_transac_8e9d99_idx')],
            },
        ),
    ]
