# Generated by Django 5.2.9 on 2026-01-28 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_coupon_order_actual_return_date_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        # Xóa tất cả payment data để tránh foreign key constraint error
        migrations.RunSQL(
            'DELETE FROM payments_payment;',
            reverse_sql=migrations.RunSQL.noop
        ),
        # Thay đổi ForeignKey từ cart.order sang orders.order
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order'),
        ),
    ]
