# Generated by Django 6.0 on 2025-12-08 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('excerpt', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.CharField(blank=True, max_length=500)),
                ('seo_keywords', models.CharField(blank=True, max_length=500)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoaiXe',
            fields=[
                ('ma_loai', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ten_loai', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Xe',
            fields=[
                ('ma_xe', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ten_xe', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('gia', models.IntegerField()),
                ('gia_khuyen_mai', models.IntegerField(blank=True, null=True)),
                ('so_luong', models.IntegerField()),
                ('mau_sac', models.CharField(max_length=50)),
                ('mo_ta_ngan', models.TextField(blank=True)),
                ('mo_ta', models.TextField(blank=True)),
                ('trang_thai', models.CharField(choices=[('in_stock', 'Còn hàng'), ('out_of_stock', 'Hết hàng')], default='in_stock', max_length=20)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.CharField(blank=True, max_length=500)),
                ('seo_keywords', models.CharField(blank=True, max_length=500)),
                ('loai_xe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.loaixe')),
            ],
        ),
    ]
