# Generated by Django 6.0 on 2025-12-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xe',
            name='gia_thue',
            field=models.IntegerField(default=0, help_text='Giá thuê mỗi ngày (VNĐ)'),
        ),
    ]
