# Generated by Django 6.0 on 2025-12-10 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_xe_gia_thue'),
    ]

    operations = [
        migrations.AddField(
            model_name='xe',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload ảnh từ máy tính', null=True, upload_to='cars/'),
        ),
    ]
