# Generated by Django 6.0 on 2025-12-10 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_xe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='xe',
            name='dung_tich_nhien_lieu',
            field=models.IntegerField(default=70, help_text='Dung tích nhiên liệu (L)'),
        ),
        migrations.AddField(
            model_name='xe',
            name='hop_so',
            field=models.CharField(choices=[('manual', 'Số sàn'), ('automatic', 'Số tự động')], default='manual', help_text='Loại hộp số', max_length=20),
        ),
        migrations.AddField(
            model_name='xe',
            name='loai_nhien_lieu',
            field=models.CharField(choices=[('gasoline', 'Xăng'), ('electric', 'Điện'), ('hybrid', 'Hybrid')], default='gasoline', help_text='Loại nhiên liệu', max_length=20),
        ),
        migrations.AddField(
            model_name='xe',
            name='so_cho',
            field=models.IntegerField(default=2, help_text='Số chỗ ngồi'),
        ),
    ]
