# Generated by Django 6.0 on 2025-12-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_xe_dung_tich_nhien_lieu_xe_hop_so_xe_loai_nhien_lieu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_dia_diem', models.CharField(help_text='Tên địa điểm', max_length=255, unique=True)),
                ('dia_chi_chi_tiet', models.TextField(blank=True, help_text='Địa chỉ chi tiết')),
                ('trang_thai', models.BooleanField(default=True, help_text='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Địa điểm',
                'verbose_name_plural': 'Địa điểm',
                'ordering': ['ten_dia_diem'],
            },
        ),
    ]
