# Generated by Django 6.0 on 2025-12-10 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload ảnh xe', upload_to='cars/')),
                ('image_url', models.URLField(blank=True, help_text='URL ảnh (nếu có)', max_length=500)),
                ('is_primary', models.BooleanField(default=False, help_text='Ảnh chính')),
                ('order', models.IntegerField(default=0, help_text='Thứ tự hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('xe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_images', to='products.xe')),
            ],
            options={
                'verbose_name': 'Ảnh xe',
                'verbose_name_plural': 'Ảnh xe',
                'ordering': ['is_primary', '-order', 'created_at'],
                'indexes': [models.Index(fields=['xe', 'is_primary'], name='products_ca_xe_id_ca95b8_idx')],
            },
        ),
    ]
