# Generated by Django 5.2.9 on 2026-03-03 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_wishlist'),
        ('tenants', '0001_tenant_init'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='wishlist',
            new_name='products_wi_user_id_f71413_idx',
            old_name='products_wi_user_id_created_idx',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blog_posts', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='carimage',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='car_images', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='loaixe',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loai_xe', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='location',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='review',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wishlists', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='xe',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='tenants.tenant'),
        ),
    ]
