# Generated by Django 6.0 on 2025-12-08 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaoHanh',
            fields=[
                ('ma_bh', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ngay_bh', models.DateField()),
                ('noi_dung', models.TextField()),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.khachhang')),
                ('xe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.xe')),
            ],
        ),
        migrations.CreateModel(
            name='HoaDonNhap',
            fields=[
                ('ma_hdn', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ngay_nhap', models.DateField()),
                ('ncc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ncc')),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.nhanvien')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietHDN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField()),
                ('don_gia', models.IntegerField()),
                ('xe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.xe')),
                ('hoa_don', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.hoadonnhap')),
            ],
        ),
        migrations.CreateModel(
            name='HoaDonXuat',
            fields=[
                ('ma_hdx', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ngay', models.DateField()),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.khachhang')),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.nhanvien')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietHDX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField()),
                ('xe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.xe')),
                ('hoa_don', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.hoadonxuat')),
            ],
        ),
    ]
