# Generated by Django 6.0 on 2025-12-23 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_cart_order_orderitem_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Mã coupon', max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('discount_type', models.CharField(choices=[('percentage', 'Phần trăm'), ('fixed', 'Số tiền cố định')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Giá trị giảm giá', max_digits=10)),
                ('min_order_value', models.DecimalField(decimal_places=2, default=0, help_text='Đơn hàng tối thiểu', max_digits=12)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Giảm tối đa (cho percentage)', max_digits=12, null=True)),
                ('valid_from', models.DateTimeField(help_text='Ngày bắt đầu hiệu lực')),
                ('valid_to', models.DateTimeField(help_text='Ngày kết thúc hiệu lực')),
                ('usage_limit', models.IntegerField(blank=True, help_text='Giới hạn số lần sử dụng', null=True)),
                ('used_count', models.IntegerField(default=0, help_text='Số lần đã sử dụng')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='actual_return_date',
            field=models.DateField(blank=True, help_text='Ngày trả xe thực tế', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='actual_return_time',
            field=models.TimeField(blank=True, help_text='Giờ trả xe thực tế', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='additional_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Phụ phí khác', max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Giá cơ bản (theo ngày/giờ)', max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, help_text='Mã coupon đã sử dụng', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Phí giao xe', max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Số tiền được giảm (từ coupon)', max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Giờ kết thúc thuê xe', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='late_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Phí trễ (nếu trả muộn)', max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Phí nhận xe', max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='rental_hours',
            field=models.IntegerField(default=0, help_text='Số giờ thuê (nếu < 1 ngày)'),
        ),
        migrations.AddField(
            model_name='order',
            name='reserved_until',
            field=models.DateTimeField(blank=True, help_text='Thời hạn giữ chỗ (timeout)', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Giờ bắt đầu thuê xe', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('reserved', 'Đã giữ chỗ'), ('processing', 'Đang xử lý'), ('paid', 'Đã thanh toán'), ('shipped', 'Đang giao'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy'), ('expired', 'Hết hạn giữ chỗ')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.coupon'),
        ),
    ]
