# Generated by Django 5.2.9 on 2026-03-02 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_coupon_order_actual_return_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='hoa_don_xuat',
            field=models.ForeignKey(blank=True, help_text='Hóa đơn xuất tự động tạo khi đơn hàng hoàn thành', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.hoadonxuat'),
        ),
    ]
