# Generated by Django 5.2.9 on 2026-03-03 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_add_hoadonxuat_to_order'),
        ('tenants', '0001_tenant_init'),
    ]

    operations = [
        migrations.AddField(
            model_name='baohanh',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bao_hanh', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='cart',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carts', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='chitiethdn',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chi_tiet_hdn', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='chitiethdx',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chi_tiet_hdx', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coupons', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='hoadonnhap',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hoa_don_nhap', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='hoadonxuat',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hoa_don_xuat', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='order',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='tenants.tenant'),
        ),
    ]
