# Generated by Django 6.0 on 2025-12-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('ma_kh', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ten', models.CharField(max_length=255)),
                ('sdt', models.CharField(max_length=20)),
                ('dia_chi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NCC',
            fields=[
                ('ma_ncc', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ten', models.CharField(max_length=255)),
                ('dia_chi', models.CharField(max_length=255)),
                ('sdt', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('ma_nv', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ten', models.CharField(max_length=255)),
                ('sdt', models.CharField(max_length=20)),
                ('dia_chi', models.CharField(max_length=255)),
                ('gioi_tinh', models.CharField(max_length=10)),
                ('ngay_sinh', models.DateField()),
                ('chuc_vu', models.CharField(max_length=100)),
            ],
        ),
    ]
