# Generated by Django 6.0 on 2025-12-22 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_verification_sent_at',
            field=models.DateTimeField(blank=True, help_text='Thời gian gửi email verification', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verification_token',
            field=models.CharField(blank=True, help_text='Token để verify email', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Email đã được xác thực chưa'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Ảnh đại diện của người dùng (upload file)', null=True, upload_to='avatars/'),
        ),
    ]
