# Generated by Django 5.2.9 on 2026-03-03 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_tenant_init'),
        ('users', '0004_add_email_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('tenant_admin', 'Tenant Admin'), ('user', 'User')], default='user', help_text='Role trong tenant (Super Admin dùng is_superuser)', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (công ty) mà user thuộc về', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_profiles', to='tenants.tenant'),
        ),
    ]
