# Generated by Django 5.2.9 on 2026-03-03 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_tenant_init'),
        ('users', '0005_tenant_init'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='khachhang',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='khach_hangs', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='ncc',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nha_cung_caps', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nhan_viens', to='tenants.tenant'),
        ),
    ]
