# Generated by Django 5.2.9 on 2026-03-03 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_code_tenant_deleted_at_tenant_status_and_more'),
        ('users', '0006_add_tenant_to_people'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Soft delete timestamp', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Hoạt động'), ('LOCKED', 'Bị khóa')], default='ACTIVE', help_text='Trạng thái tài khoản: ACTIVE, LOCKED', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('TENANT_ADMIN', 'Tenant Admin'), ('STAFF', 'Nhân viên'), ('CUSTOMER', 'Khách hàng')], default='CUSTOMER', help_text='Vai trò: SUPER_ADMIN, TENANT_ADMIN, STAFF, CUSTOMER', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (công ty) mà user thuộc về. Null nếu là SUPER_ADMIN', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_profiles', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['tenant', 'role'], name='users_userp_tenant__b93f38_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['tenant', 'status'], name='users_userp_tenant__c28234_idx'),
        ),
    ]
